### ISSUE TITLE
no auto-retry on connect?

### ISSUE THREAD

**Issue by xenoterracide** [guidesmiths/rascal#108]
in the very initiall attempt to make a connection, there's no auto retry? in fact this seems to have halted my startup entirely... which means it's not rejecting the promise? our rabbit server takes much longer to come up than our client servers.

```
  rascal:config:configure Configuring vhost: / +0ms
  rascal:config:configure Configuring exchange: amq.topic +18ms
  rascal:config:configure Configuring exchange:  +0ms
  rascal:config:configure Configuring queue: /device.deliverable.subscription +0ms
  rascal:config:configure Configuring binding: device.deliverable.subscription +15ms
  rascal:config:configure Configuring subscription: DeviceDeliverableSubscription +1ms
  rascal:config:configure Configuring publication: /amq.topic +2ms
  rascal:config:configure Configuring publication: / +0ms
  rascal:config:configure Configuring publication: //device.deliverable.subscription +15ms
  rascal:config:configure Configuring subscription: DeviceDeliverableSubscription +0ms
  rascal:config:configure Configuring subscription: //device.deliverable.subscription +0ms
  rascal:config:configure Configuring counter: stub +17ms
  rascal:Broker Initialising broker +0ms
  rascal:Vhost Initialising vhost: / +0ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://localhost +0ms
error:    Error: Failed to connect to: amqp://localhost. Original message was: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/Users/calebcushing/IdeaProjects/service-graph/node_modules/amqplib/lib/connection.js:260:17)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
info:     connected to postgres://localhost:5432/briggo_production
info:     connected to amqp://localhost # actually this is from my homegrown thing that I'm replacing with rascal
^C
```

my workaround/solution for now is to use `cockatiel`

```ts
import { ConsecutiveBreaker, Policy } from 'cockatiel/dist';
...

    const retry = Policy.handleAll().retry().exponential({});
    const circuitBreaker = Policy.handleAll().circuitBreaker(
      10 * 1000,
      new ConsecutiveBreaker(100),
    );
    circuitBreaker.onBreak((data) => {
      this.log.error(`${basename(__filename)} breaker tripped %O`, data);
    });
    circuitBreaker.onReset((data) => {
      this.log.debug(`${basename(__filename)} breaker reset %j`, data);
    });
    const retryWithBreaker = Policy.wrap(retry, circuitBreaker);
    const broker = await retryWithBreaker.execute(() => rascal.BrokerAsPromised.create(config));
```

**Comment by cressie176** [comment]
There's no auto-retry on the initial connect. If RabbitMQ isn't available on startup then the likelihood is that you have a configuration error rather than a network error/broker error, so I prefer to fail fast and loud rather than have rascal attempt to reconnect.

For example, Imagine if you have 3 instances of an application on version 1. You attempt to release version 2, but somehow the connection configuration was broken, and the application no longer connects. With the fail fast behaviour, a rolling upgrade will detect the issue and stop before replacing all 3 instances. If instead rascal attempted to reconnect, it would be harder for the deployment system to detect the problem and you would risk replacing all working instances, causing an outage.
