### ISSUE TITLE
Killing RabbitMQ Cluster down crashes app

### ISSUE THREAD

**Issue by willthrom** [guidesmiths/rascal#117]
```
17/08/2020 12:25:28/app/node_modules/pino/lib/tools.js:55
17/08/2020 12:25:28      this[writeSym](o, format(msg, formatParams, this[formatOptsSym]), level)
17/08/2020 12:25:28                    ^
17/08/2020 12:25:28
17/08/2020 12:25:28TypeError: this[writeSym] is not a function
17/08/2020 12:25:28    at SubscriberSession.LOG (/app/node_modules/pino/lib/tools.js:55:21)
17/08/2020 12:25:28    at SubscriberSession.emit (events.js:310:20)
17/08/2020 12:25:28    at handleChannelError (/app/node_modules/rascal/lib/amqp/Subscription.js:255:13)
17/08/2020 12:25:28    at Connection.<anonymous> (/app/node_modules/lodash/lodash.js:10076:25)
17/08/2020 12:25:28    at Object.onceWrapper (events.js:417:26)
17/08/2020 12:25:28    at Connection.emit (events.js:322:22)
17/08/2020 12:25:28    at Connection.C.onSocketError (/app/node_modules/amqplib/lib/connection.js:353:10)
17/08/2020 12:25:28    at Socket.emit (events.js:322:22)
17/08/2020 12:25:28    at emitErrorNT (internal/streams/destroy.js:92:8)
17/08/2020 12:25:28    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
17/08/2020 12:25:28    at processTicksAndRejections (internal/process/task_queues.js:84:21)
17/08/2020 12:25:28npm ERR! code ELIFECYCLE
17/08/2020 12:25:28npm ERR! errno 1
```

no sending message, just shutting down the RabbitMQ cluster after the app has created the queues.

It is odd thought, when the app restarts (Rancher) we get  (RabbitMQ still down):
```
17/08/2020 12:27:45(node:23) UnhandledPromiseRejectionWarning: Error: Failed to connect to: amqp://guest:***@rabbitmq.infrastructure:5674. Original message was: connect EHOSTUNREACH 10.17.6.41:5674
17/08/2020 12:27:45    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
17/08/2020 12:27:45(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
17/08/2020 12:27:45(node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It seems our developer guys are not handling properly that, where should we check?

It goes without saying, when I start the RabbitMq Cluster, no connections are created, even when I added to the code:

```
const BROKER_CONF = {
  vhosts: {},

  defaults: {
    vhosts: {
      queues: {
        assert: true,
        options: {
          durable: true
        }
      }
    }
  }
}

BROKER_CONF.vhosts[VHOST] = {
  connectionStrategy: "fixed",
  connections: CFG.QUEUE.HOSTS.map(h => ({
    hostname: h.split(':')[0],
    port: h.split(':')[1] || 5672,
    user: CFG.QUEUE.USER,
    password: CFG.QUEUE.PASS,
    retry: {
      min: 1000,
      max: 5000,
      strategy: "linear"
    }
  })),
```

What are we missing?

Thanks in advance!

**Comment by cressie176** [comment]
Hi @willthrom,

The initial error doesn't look like a problem with Rascal. It's simply [emitting](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/Subscription.js#L255) an error, which pino is failing to log. This is mostly likely to be a problem with how you are using pino, or potentially with pino itself.

Regarding your second problem, to avoid unhandled rejections you need to handle all of the error events documented [here](https://github.com/guidesmiths/rascal#very-important-section-about-event-handling).

**Comment by willthrom** [comment]
Hi,
Thanks for the quick response.
It seems it was handled except trying to subscribe to a broker which couldn't connect to RabbitMQ.

I fixed that however, I don't see the retry working, only one time message:
17/08/2020 14:11:15{"level":50,"time":1597669875638,"msg":"Creating Broker: Failed to connect to: amqp://guest:***@rabbitmq.infrastructure:5674. Original message was: connect EHOSTUNREACH 10.5.1.31:5674"}

which make sense as that was the Catch from the TRY.  I am a little lost with the broker flow, I will read the documentation again and check with the developer, because it the broken connect fails to reach rabbitMQ should try later (retry policy), not return an exception...

```
const connect = async () => {
  if(broker !== null) {
    logger.warn('AMQP broker already connected')
    return
  }
  try {
  broker = await Broker.create(BROKER_CONF) 
    broker.on('error', (err, { vhost, connectionUrl }) => {
      logger.error('Broker error', err, vhost, connectionUrl)
    })
  } catch (e) {
    logger.error('Creating Broker: ' + (e.message || e.toString() || e))
  }
}```

**Comment by cressie176** [comment]
Retries only work once you've successfully connected at least once.

**Comment by willthrom** [comment]
Thanks, we will handle that.
