### ISSUE TITLE
App constantly crashes when using the debugger for more then a few seconds with rascal connected.

### ISSUE THREAD

**Issue by brandoncollins7** [guidesmiths/rascal#131]
Ever since adding rascal to my project I am unable to properly use my debugger breakpoints, if I hold the execution for more then a few seconds my application will crash and completely stop making debugging near impossible.

Error: Unexpected close
    at succeed (C:\Users\Documents\Projects\MyProject\MyProject-api-server\node_modules\amqplib\lib\connection.js:272:13)
    at onOpenOk (C:\Users\Documents\Projects\MyProject\MyProject-api-server\node_modules\amqplib\lib\connection.js:254:5)
    at C:\Users\Documents\Projects\MyProject\MyProject-api-server\node_modules\amqplib\lib\connection.js:166:32
    at C:\Users\Documents\Projects\MyProject\MyProject-api-server\node_modules\amqplib\lib\connection.js:160:12
    at Socket.recv (C:\Users\Documents\Projects\MyProject\MyProject-api-server\node_modules\amqplib\lib\connection.js:499:12)
    at Object.onceWrapper (events.js:427:28)
    at Socket.emit (events.js:321:20)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at emitReadable_ (_stream_readable.js:558:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
Emitted 'error' event on Vhost instance at:
    at handleConnectionError (C:\Users\Documents\Projects\MyProject\MyProject-api-server\node_modules\rascal\lib\amqp\Vhost.js:404:10)
    at CallbackModel.<anonymous> (C:\Users\Documents\Projects\MyProject\MyProject-api-server\node_modules\rascal\node_modules\lodash\lodash.js:10076:25)
    at CallbackModel.emit (events.js:321:20)
    at CallbackModel.EventEmitter.emit (domain.js:485:12)
    at Connection.emit (events.js:321:20)
    at Connection.EventEmitter.emit (domain.js:485:12)
    at Connection.C.onSocketError (C:\Users\Documents\Projects\MyProject\MyProject-api-server\node_modules\amqplib\lib\connection.js:353:10)
    at Socket.emit (events.js:333:22)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by cressie176** [comment]
Hi @brandoncollins7,

This is likely because while paused amqplib cannot send or receive [heartbeats](http://www.squaremobius.net/amqp.node/channel_api.html#heartbeating). You will need to disable* heartbeats, or make the interval very large if you want to pause connections. See [connection config](https://github.com/guidesmiths/rascal#connection)

*Unfortunately there is no way to disable heartbeats from the client, but if you set the interval to 0, amqplib will honour the server heartbeat.

**Comment by cressie176** [comment]
Also, if your application is crashing, rather than attempting to automatically recover, this suggests you are missing an [error handler](https://github.com/guidesmiths/rascal#very-important-section-about-event-handling)

**Comment by brandoncollins7** [comment]
Ah yes, that solved the problem, thank you:D
