### ISSUE TITLE
Node JS service is restarting with dumping some Emitted 'error' event on Vhost instance at error.

### ISSUE THREAD

**Issue by mayankmike86** [guidesmiths/rascal#135]
Hi We are using rascal with our nodeJS app. It is working fine from last 1 month, but all of a sudden node app is crashing with below error dumped in logs and not catching the issue any where although all places(connection creation, msg publishing and msg subscribe) is guarded with catch blocks. 
Although i saw that one message was published successfully before service restarted.

errormessage:
```
2020-10-23T18:57:04.583553319Z events.js:288
2020-10-23T18:57:04.583587269Z       throw er; // Unhandled 'error' event
2020-10-23T18:57:04.583596694Z       ^
2020-10-23T18:57:04.583603817Z 
2020-10-23T18:57:04.583612233Z Error: read ECONNRESET
2020-10-23T18:57:04.583619655Z     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
2020-10-23T18:57:04.583627246Z Emitted 'error' event on Vhost instance at:
2020-10-23T18:57:04.583633477Z     at handleConnectionError (/usr/src/app/node_modules/rascal/lib/amqp/Vhost.js:364:10)
2020-10-23T18:57:04.583640901Z     at CallbackModel.<anonymous> (/usr/src/app/node_modules/lodash/lodash.js:10076:25)
2020-10-23T18:57:04.583647851Z     at Object.onceWrapper (events.js:418:26)
2020-10-23T18:57:04.583654856Z     at CallbackModel.emit (events.js:311:20)
2020-10-23T18:57:04.583661298Z     at CallbackModel.EventEmitter.emit (domain.js:482:12)
2020-10-23T18:57:04.583669758Z     at Connection.emit (events.js:311:20)
2020-10-23T18:57:04.583676217Z     at Connection.EventEmitter.emit (domain.js:482:12)
2020-10-23T18:57:04.583684842Z     at Connection.C.onSocketError (/usr/src/app/node_modules/amqplib/lib/connection.js:353:10)
2020-10-23T18:57:04.583693334Z     at TLSSocket.emit (events.js:323:22)
2020-10-23T18:57:04.583701378Z     at TLSSocket.EventEmitter.emit (domain.js:482:12)
2020-10-23T18:57:04.583708081Z     at emitErrorNT (internal/streams/destroy.js:92:8)
2020-10-23T18:57:04.583715372Z     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
2020-10-23T18:57:04.583722416Z     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
2020-10-23T18:57:04.583730876Z   errno: 'ECONNRESET',
2020-10-23T18:57:04.583738292Z   code: 'ECONNRESET',
2020-10-23T18:57:04.583745597Z   syscall: 'read'
2020-10-23T18:57:04.583753156Z }
```

PS: My connection configuration is
`"connection": {
                "heartbeat": 5,
                "socketOptions": {
                    "timeout": 20000
                },
                "slashes": true
            }`

**Comment by cressie176** [comment]
Hi @mayankmike86,

Try/Catch blocks are insufficient. You need to register error listeners. See the [very important section about event handling](https://github.com/guidesmiths/rascal#very-important-section-about-event-handling)

**Comment by mayankmike86** [comment]
Thanks @cressie176 I missed the error listeners on broker creation, added it now.
