### ISSUE TITLE
Application is getting restarted suddenly on broker creation with Error: Unexpected close!

### ISSUE THREAD

**Issue by mayankmike86** [guidesmiths/rascal#136]
Same issue for me all of a sudden its causing server restarts..Although I have guarded with .on(error.. check at all places as per the documentation.

NOTE: Is it right to throw err on error event, as in documentation I can see it is just always logged and not thrown back to callee method...is this I am doing wrong?

```js
 broker.on('error', (err) => {
            logger.error('Error occured during broker creation..');
            throw err;
        });
2020-11-09T09:48:38.713648848Z 2020-11-09T09:48:38.71 <ERROR> Error occured during broker creation.. (in rabbitmq-client.js:28)
2020-11-09T09:48:38.713717495Z Call Stack:
2020-11-09T09:48:38.713730503Z     at Vhost.<anonymous> (/xxxxxx/xxxxxx/xxxx/src/data_access/rabbitmq-client.js:28:20)
2020-11-09T09:48:38.713752936Z     at Vhost.emit (events.js:311:20)
2020-11-09T09:48:38.713762558Z     at Vhost.EventEmitter.emit (domain.js:482:12)
2020-11-09T09:48:38.713770793Z     at handleConnectionError (/usr/src/app/node_modules/rascal/lib/amqp/Vhost.js:364:10)
2020-11-09T09:48:38.713781776Z     at CallbackModel.<anonymous> (/usr/src/app/node_modules/lodash/lodash.js:10076:25)
2020-11-09T09:48:38.713844703Z     at Object.onceWrapper (events.js:418:26)
2020-11-09T09:48:38.713854975Z     at CallbackModel.emit (events.js:311:20)
2020-11-09T09:48:38.713862712Z     at CallbackModel.EventEmitter.emit (domain.js:482:12)
2020-11-09T09:48:38.713871696Z     at Connection.emit (events.js:311:20)
2020-11-09T09:48:38.713879162Z     at Connection.EventEmitter.emit (domain.js:482:12)
2020-11-09T09:48:38.713887140Z     at Connection.C.onSocketError (/usr/src/app/node_modules/amqplib/lib/connection.js:353:10)
2020-11-09T09:48:38.713895297Z     at TLSSocket.emit (events.js:323:22)
2020-11-09T09:48:38.713904148Z     at TLSSocket.EventEmitter.emit (domain.js:482:12)
2020-11-09T09:48:38.713912097Z     at endReadableNT (_stream_readable.js:1204:12)
2020-11-09T09:48:38.713920059Z     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-11-09T09:48:38.715639414Z xxxxxx/xxx/xxx/xx/src/data_access/rabbitmq-client.js:29
2020-11-09T09:48:38.715666633Z             throw err;
2020-11-09T09:48:38.715728936Z             ^
2020-11-09T09:48:38.715737512Z 
2020-11-09T09:48:38.715746423Z Error: Unexpected close
2020-11-09T09:48:38.715753795Z     at succeed (/usr/src/app/node_modules/amqplib/lib/connection.js:272:13)
2020-11-09T09:48:38.715763604Z     at onOpenOk (/usr/src/app/node_modules/amqplib/lib/connection.js:254:5)
2020-11-09T09:48:38.715771744Z     at /usr/src/app/node_modules/amqplib/lib/connection.js:166:32
2020-11-09T09:48:38.715780274Z     at /usr/src/app/node_modules/amqplib/lib/connection.js:160:12
2020-11-09T09:48:38.715787709Z     at TLSSocket.recv (/usr/src/app/node_modules/amqplib/lib/connection.js:499:12)
2020-11-09T09:48:38.715839122Z     at Object.onceWrapper (events.js:417:28)
2020-11-09T09:48:38.715851042Z     at TLSSocket.emit (events.js:311:20)
2020-11-09T09:48:38.715860289Z     at TLSSocket.EventEmitter.emit (domain.js:482:12)
2020-11-09T09:48:38.715868645Z     at emitReadable_ (_stream_readable.js:562:12)
2020-11-09T09:48:38.715886918Z     at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

Please help!

**Comment by cressie176** [comment]
Hi @mayankmike86,

I see you've already posted this to https://github.com/squaremo/amqp.node/issues/151. Please be sure to read the [this comment](https://github.com/squaremo/amqp.node/issues/151#issuecomment-332443577) in that issue which will hopefully shed some light on the background behind `Unexpected Close`.

Regarding Rascal, 

```
 broker.on('error', (err) => {
  logger.error('Error occured during broker creation..');
  throw err;
});
```

The above code is wrong. An error event doesn't happen when the broker is created, but will be emitted if the connection errors later on. What I normally do is log the error, and then trust Rascal's automatically reconnection logic to fix things.

**Comment by cressie176** [comment]
Closing due to inactivity
