### ISSUE TITLE
Subscribers are lost when rabbitmq is killed

### ISSUE THREAD

**Issue by nik-vaidya** [guidesmiths/rascal#142]
Hi,
With reference to [https://github.com/guidesmiths/rascal/issues/18](url)

We are using rascal(8.0.0) and we encounter the same error which is mentioned in the above issue. This is the log I saw on my server
`SubscriberSession.<anonymous>:47 - LOG Error was :: Connection closed: 320 (CONNECTION-FORCED) with message "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"`

After getting this error, We opened up rabbitmq console and found that the queue was intact(queue created from my rascal configuration file) but there were no consumers.

We already see that the above issue is fixed in version 1.4 as part of [https://github.com/guidesmiths/rascal/issues/18](url).
FYI currently, we are seeing this only for subscribers.

**Comment by cressie176** [comment]
Hi @nik-vaidya,

If I start the example application then run restart my rabbitmq docker container after a couple of seconds I get output posted below. You'll see the same `Connection closed: 320 (CONNECTION-FORCED) with message "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'` error, but after a short while the subscriber recovers.

I took a look through the rascal changelog and didn't see anything suggesting there were any fixes after version 8.0.0 so my best guess is that either there's something unusual with way you're setting up subscribers, or that I failed to document a fix. Can I suggest 

- comparing your application to the simple example
- testing with DEBUG=rascal:* to see what the subscriber is doing
- confirming that you have configured the subscriber to [retry](https://github.com/guidesmiths/rascal/blob/master/lib/config/baseline.js#L80-L85)
- trying with the latest version of rascal

```
cd examples/simple
DEBUG=rascal:* node index

  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 0, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Borrowed confirm channel: 86ce96d0-6e46-4184-981a-9498afe6c19a. { vhost: '/', mode: 'confirm', queue: 0, size: 1, available: 0, borrowed: 1, min: 1, max: 5 } +0ms
  rascal:Publication Publishing 37 bytes to confirm exchange: demo_ex with routingKeys: a.b.c +1s
  rascal:Vhost Releasing confirm channel: 86ce96d0-6e46-4184-981a-9498afe6c19a. { vhost: '/', mode: 'confirm', queue: 0, size: 1, available: 0, borrowed: 1, min: 1, max: 5 } +3ms
  rascal:Subscription Received message: ec08fdef-805c-4b33-b5b3-243c4105f66f from queue: demo_q +1s
2021-02-25T15:20:15.977Z: hello world
  rascal:SubscriberSession Acknowledging message: ec08fdef-805c-4b33-b5b3-243c4105f66f on channel: 5a496466-9f46-4a4b-95c3-7ee197316992 +1s
  rascal:SubscriberSession Removing channel: 5a496466-9f46-4a4b-95c3-7ee197316992 from session +378ms
  rascal:Vhost Handling connection error: Connection closed: 320 (CONNECTION-FORCED) with message "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'" initially from connection: 73984960-ea88-4441-bfb9-3a1d91667feb, amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +380ms
{ Error: Connection closed: 320 (CONNECTION-FORCED) with message "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
    at Object.accept (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:91:15)
    at Connection.mainAccept (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:478:48)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 320 } { vhost: '/',
  connectionUrl:
   'amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100' }
  rascal:Vhost Initialising vhost: / +0ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +9s
  rascal:Subscription Handling channel error: Connection closed: 320 (CONNECTION-FORCED) with message "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'" from demo_sub using channel: null +381ms
{ Error: Connection closed: 320 (CONNECTION-FORCED) with message "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
    at Object.accept (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:91:15)
    at Connection.mainAccept (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:478:48)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 320 }
  rascal:Subscription Subscribing to queue: demo_q +0ms
  rascal:Vhost Requested channel. Outstanding channel requests: 1 +1ms
  rascal:Vhost Will attempt reconnection in in 1254ms +3ms
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 0, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +616ms
  rascal:Vhost Handling connection error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: Socket closed abruptly during opening handshake initially from connection: 73984960-ea88-4441-bfb9-3a1d91667feb, amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +643ms
Error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:260:17)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) { vhost: '/',
  connectionUrl:
   'amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100' }
  rascal:Vhost Initialising vhost: / +0ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +1s
  rascal:Vhost Will attempt reconnection in in 3730ms +2ms
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 1, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +358ms
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 2, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 3, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 4, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Handling connection error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: Socket closed abruptly during opening handshake initially from connection: 73984960-ea88-4441-bfb9-3a1d91667feb, amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +369ms
Error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:260:17)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) { vhost: '/',
  connectionUrl:
   'amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100' }
  rascal:Vhost Initialising vhost: / +0ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +4s
  rascal:Vhost Will attempt reconnection in in 6797ms +3ms
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 5, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +628ms
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 6, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 7, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 8, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 9, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 10, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 11, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Handling connection error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: Socket closed abruptly during opening handshake initially from connection: 73984960-ea88-4441-bfb9-3a1d91667feb, amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +165ms
Error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:260:17)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) { vhost: '/',
  connectionUrl:
   'amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100' }
  rascal:Vhost Initialising vhost: / +1ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +7s
  rascal:Vhost Will attempt reconnection in in 8416ms +3ms
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 12, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +831ms
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 13, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 14, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 15, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 16, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 17, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 18, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Requested confirm channel. { vhost: '/', mode: 'confirm', queue: 19, size: 1, available: 1, borrowed: 0, min: 1, max: 5 } +1s
  rascal:Vhost Handling connection error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: Socket closed abruptly during opening handshake initially from connection: 73984960-ea88-4441-bfb9-3a1d91667feb, amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +580ms
Error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:260:17)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) { vhost: '/',
  connectionUrl:
   'amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100' }
  rascal:Vhost Initialising vhost: / +0ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +8s
  rascal:tasks:createConnection Obtained connection: d44a5af7-f120-4760-80a8-d233f24b4510 +11ms
  rascal:tasks:createChannel Creating channel +30s
  rascal:tasks:assertExchanges Asserting exchange: demo_ex +30s
  rascal:tasks:assertQueues Asserting queue: demo_q +30s
  rascal:tasks:applyBindings Binding queue: demo_q to exchange: demo_ex with binding key: a.b.c +30s
  rascal:tasks:closeChannel Closing channel +30s
  rascal:Vhost vhost: / was initialised with connection: d44a5af7-f120-4760-80a8-d233f24b4510 +21ms
  rascal:Vhost Destroying channel: 86ce96d0-6e46-4184-981a-9498afe6c19a +0ms
  rascal:Vhost Creating pooled confirm channel for vhost: / +0ms
  rascal:Vhost Created confirm channel: 0e425d1b-2c36-42ec-9f6a-2f3bb514aa85 from connection: d44a5af7-f120-4760-80a8-d233f24b4510 +4ms
  rascal:Vhost Created confirm channel: 1bb08629-44f5-42fe-9fd9-68ca6987f073 from connection: d44a5af7-f120-4760-80a8-d233f24b4510 +1ms
  rascal:Vhost Borrowed confirm channel: 1bb08629-44f5-42fe-9fd9-68ca6987f073. { vhost: '/', mode: 'confirm', queue: 19, size: 1, available: 0, borrowed: 1, min: 1, max: 5 } +0ms
  rascal:Publication Publishing 37 bytes to confirm exchange: demo_ex with routingKeys: a.b.c +21s
  rascal:Vhost Creating pooled confirm channel for vhost: / +1ms
  rascal:Vhost Releasing confirm channel: 1bb08629-44f5-42fe-9fd9-68ca6987f073. { vhost: '/', mode: 'confirm', queue: 18, size: 2, available: 0, borrowed: 1, min: 1, max: 5 } +2ms
  rascal:Vhost Borrowed confirm channel: 1bb08629-44f5-42fe-9fd9-68ca6987f073. { vhost: '/', mode: 'confirm', queue: 18, size: 2, available: 0, borrowed: 1, min: 1, max: 5 } +0ms
  rascal:Publication Publishing 37 bytes to confirm exchange: demo_ex with routingKeys: a.b.c +3ms
  rascal:SubscriberSession Opening subscriber session: amq.ctag-w54cSVaspu2UgYyFFPkSTg on channel: 0e425d1b-2c36-42ec-9f6a-2f3bb514aa85 +20s
  rascal:Subscription Received message: fe3853e7-9dba-4939-bc30-f14d0ea05e2d from queue: demo_q +20s
2021-02-25T15:20:16.981Z: hello world
  rascal:SubscriberSession Acknowledging message: fe3853e7-9dba-4939-bc30-f14d0ea05e2d on channel: 0e425d1b-2c36-42ec-9f6a-2f3bb514aa85 +0ms
```

**Comment by nik-vaidya** [comment]
Hi @cressie176,
Below is the rascal config file we are using
`{
  "vhosts": {
    "/": {
      "connection": {
        "options": {
          "heartbeat": 10,
          "connection_timeout": 60000
        },
        "retry": {
          "min": 1000,
          "max": 60000,
          "factor": 2,
          "strategy": 'exponential'
        },
        "socketOptions": {
          "timeout": 10000
        }
      },
      "exchanges": [
        "test_service", "test", "test_sync", "test_response"
      ],
      "queues": {
        "queue1": {
          "options": {
            "arguments": {
              "x-message-ttl": 3600000,
              "x-dead-letter-exchange": "queue1_dead_exchange",
              "durable": true
            }
          }
        },
        "queue2": {
          "options": {
            "arguments": {
              "x-message-ttl": 3600000,
              "x-dead-letter-exchange": "queue2_dead_exchange",
              "durable": true
            }
          }
        }
      },
      "bindings": ["test[key] -> queue1",
        "test_response[key] -> queue2",],
      "publications": {
        "test_service": {
          "exchange": "test_service",
          "routingKey": "r1",
        },
        "test_sync": {
          "exchange": "test_sync",
          "routingKey": "r2"
        }
      },
      "subscriptions": {
        "queue1": {
          "queue": "queue1"
        },
        "queue2": {
          "queue": "queue2"
        }
      }
    }
  }
}`

Actually, we observed this issue in some environments, and in some of the env subscriber is recovering. So what should be the reasons when we will lose a subscriber. So in which cases we should subscribe again and is there any way to get subscription information in rascal?

Thank you in advance

**Comment by cressie176** [comment]
You can use
```js
console.log(JSON.stringify(subscription.config, null, 2));
```
To view the subscription configuration. This will show you the final state once any defaults have been applied.

You can lose a subscriber for several reasons:

1. Channel error (e.g. you acknowledge a message twice)
1. Connection error
1. Connection close 
1. A Queue was deleted or becomes unavailable - see [cancel notification](https://www.rabbitmq.com/consumer-cancel.html)

To obtain more information please try running your application with the `DEBUG` environment variable set to `rascal:*` and inspect the output to learn why the subscriber is not recovering. You should see output like the following...

```
rascal:Subscription Subscribing to queue: demo_q +0ms
```

There's would also urge you to upgrade to the latest version of rascal. The [changelog](https://github.com/guidesmiths/rascal/blob/master/CHANGELOG.md) will inform you of any breaking changes, and providing you are using a recent version of Node.js the API changes are minor.

**Comment by nik-vaidya** [comment]
Okay.
I updated the rascal version. I will debug furthermore if I get the same issue.
Meanwhile is there any way provided by rascal to check if subscriptions are intact or not?

**Comment by cressie176** [comment]
> Meanwhile is there any way provided by rascal to check if subscriptions are intact or not?

When you subscribe, you are returned a "SubscriberSession". If you've followed [the very important section about event handling](https://github.com/guidesmiths/rascal#very-important-section-about-event-handling), you will have already registered an error listener, which will warn you that the channel errored or closed while the rascal was still subscribed. You can also listen for a `subscribed` event which is emitted whenever rascal successfully subscribes.

You could use put a setTimeout in the error event listener, which you cleared in the subscribed event listener to report if a subscription was not recreated within a period of time. e.g.

```js
const session = await broker.subcribe(....)
let timerId;
session.on('error', () => {
  timerId = setTimeout(() => console.error('Subscriber did not recover'), 60000).unref();
})
session.on('subscribed', () => {
  clearTimeout(timerId);
})
```

Thinking about event handling, one thing which could be causing your issue is if you aren't listening to all the rascal error handlers, but elsewhere in your application you have registered `process.uncaughtException` or `uncaughtException.unhandledRejection` listeners in order to stop your application crashing. Doing the above could prevent Rascal from re-consuming after a connection error.

**Comment by nik-vaidya** [comment]
Yeah, I tested it. I did not find this issue again. But I updated the rascal version while testing.

**Comment by cressie176** [comment]
OK. Happy to leave the issue open for another week to see if it occurs again.

**Comment by nik-vaidya** [comment]
Hi @cressie176 

There is one more thing about the `persistent ` option while publishing the message. Earlier I use to add this as part of the rascal config file. Can I send this option like 
`broker.publish(publication, message, { options: { "persistent": true ,"headers": {} } })`

Also as per the documentation, if we set it to `true` then messages will be discarded if the rabbit restart. If we keep it false and if we lost consumers. Then do the unconsumed messages will cause to rabbitmq capacity exhaust? And what is the default value if we do not pass as an option?

**Comment by cressie176** [comment]
Hi @nik-vaidya,

With rascal, publications are persistent by [default](https://github.com/guidesmiths/rascal/blob/master/lib/config/baseline.js#L73). You can override this in the publication configuration, or when you publish the message, as you describe, although I think you got your logic wrong - if you set it to true, then the message will **not** be discarded is RabbitMQ restarts.

If you continue to publish messages to RabbitMQ, but never consume them, eventually you will run out of capacity (my guess is memory will run out before disk space). If when you publish, you use confirm channels, then RabbitMQ will only send an acknowledgement once a persistent message has been successfully written to disk. Consequently you should not lose messages.

It is also advisable to monitor queue lengths and alert when they grow beyond a certain point.
