### ISSUE TITLE
Error on publish confirm

### ISSUE THREAD

**Issue by PaoloLaurenti** [guidesmiths/rascal#41]
I am trying to publish a message using publish confirm with a publication with `mandatory: true` flag.
Every time I try to publish a message I get the following error:
```console
Error was:  { TypeError: Cannot read property 'messageId' of undefined
    at EventEmitter.publication.on.on.on (/home/paolo/dev/rabbitMQ-producer.js:15:67)
    at EventEmitter.emit (events.js:189:13)
    at ConfirmChannel.emit (events.js:189:13)
    at /home/paolo/dev/node_modules/amqplib/lib/channel.js:273:10
    at ConfirmChannel.content [as handleMessage] (/home/paolo/dev/node_modules/amqplib/lib/channel.js:326:9)
    at ConfirmChannel.C.acceptMessageFrame (/home/paolo/dev/node_modules/amqplib/lib/channel.js:241:31)
    at ConfirmChannel.C.accept (/home/paolo/dev/node_modules/amqplib/lib/channel.js:394:17)
    at Connection.mainAccept [as accept] (/home/paolo/dev/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/home/paolo/dev/node_modules/amqplib/lib/connection.js:478:48)
    at Socket.emit (events.js:189:13)
    at emitReadable_ (_stream_readable.js:535:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 541 }
```

If I set `mandatory: false` everything is fine.

My configurations are:

```
exchanges: {
  messages: {
    assert: true,
    check: true,
    type: 'fanout',
    options: {
      durable: true,
      autoDelete: false
     }
   }
 }
```
and

```
      publications: {
        messages_pub: {
          exchange: 'messages',
          routingKey: '#',
          confirm: true,
          options: {
            persistent: true,
            mandatory: true
          }
        }
      }
```

The exchange where I am publishing messages has no queues bound.

Rascal: 4.1.0
RabbitMQ: 3.7.8

**Comment by cressie176** [comment]
Hi @PaoloLaurenti can you share the code from `rabbitMQ-producer.js:15:67` please?

**Comment by cressie176** [comment]
On a separate note there's not point both checking and asserting the queues

**Comment by PaoloLaurenti** [comment]
Hi @cressie176, 
here's the `rabbitMQ-producer.js` file content:

```js
function RabbitMQProducer (broker, publicationName) {
  this.broker = broker
  this.publicationName = publicationName

  this.publish = async function (message) {
    const publication = await this.broker.publish(this.publicationName, JSON.stringify(message))
    publication
      .on('success', messageId => {
        console.log('Message id was: ', messageId)
      })
      .on('error', (err, messageId) => {
        console.error('Error was: ', err)
      })
      .on('return', (messageId) => {
        console.warn('Message was returned: ', message.properties.messageId)
      })
  }
}

module.exports = RabbitMQProducer
```

The given `broker` object is created via this function:
```js
async function setupRabbitMQBroker (rascalConfig, listener) {
  const broker = await rascal.BrokerAsPromised.create(rascal.withDefaultConfig(rascalConfig))
  broker.on('error', console.error)
  return broker
}
```

**Comment by PaoloLaurenti** [comment]
> On a separate note there's not point both checking and asserting the exchange

Oh, OK, that's true. Thanks for the suggestion :+1:

**Comment by cressie176** [comment]
Here's your problem...

```
      .on('return', (messageId) => {
        console.warn('Message was returned: ', message.properties.messageId)
      })
```

**Comment by PaoloLaurenti** [comment]
Oh man... you're right...  
I am really sorry. :pray: 

Thank you very much

**Comment by cressie176** [comment]
Don't worry. Happens to us all, especially when getting familiar with a new library.
